/*Wedding database for guest info*/
DROP TABLE IF EXISTS GUEST;

CREATE TABLE GUEST(
	ID INT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR (25) NOT NULL,
	LASTNAME VARCHAR (25) NOT NULL,
	EMAIL VARCHAR(125),
	ADULTS INT(2) NOT NULL,
	KIDS INT(2),
	TOTALQUANITY INT(2) NOT NULL,
	PRIMARY KEY (ID)
);
